config_version: 2

# Enable debug mode (output additional messages to the console)
debug: false

# Settings for messages and sounds when a player is infected
if-player-infected:
  # Enable displaying the infection message
  message: false
  # Enable playing the sound when infected
  play-sound: false
  # Update the timer when infected
  update-timer: true

# Number of times the effect will be applied
effect-will-applied-after: 5

# Delay in server ticks before executing the first repeat (n * 20)
delay: 5

# Period in server ticks for task repetition (n * 20)
period: 5

# Enable a random time range for effect application
random_time_from_range:
  # Enable a random time range
  enable: true
  # Lower limit of the time range in seconds
  range_from: 5
  # Upper limit of the time range in seconds
  range_to: 10

# Settings for potions that will be given
potion-gived:
  # Settings for poison potion
  POISON:
    # Potion duration in seconds (n * 20 ticks)
    potion-duration: 60
  # Settings for blindness potion
  BLINDNESS:
    # Potion duration in seconds (n * 20 ticks)
    potion-duration: 5
  # Settings for hunger potion
  HUNGER:
    # Potion duration in seconds (n * 20 ticks)
    potion-duration: 30

# Settings for sounds that will be played
sound-played:
  # Enable the sound when attacked
  sound-in-attack:
    # Enable the attack sound
    enable: true
    # Sound name from Minecraft resources
    sound: "AMBIENT_CAVE"
    # Sound volume (from 0 to 100)
    volume: 100.0
    # Sound pitch (from 0 to 2)
    pitch: 1.0
  # Enable the sound when the effect is given
  sound-in-effect-gived:
    # Enable the effect sound
    enable: true
    # Sound name from Minecraft resources
    sound: "ENTITY_ENDERMEN_DEATH"
    # Sound volume (from 0 to 100)
    volume: 100.0
    # Sound pitch (from 0 to 2)
    pitch: 1.0

# Messages for different events
messages:
  # Plugin reload success message
  plugin_reload: "§2Plugin successfully reloaded"
  # Insufficient permissions message
  no_permission: "§cYou do not have permission"
  # Missing subcommand message
  no_command_args: "§cUsage: /%s <subcommand> <args>"
  # Invalid command message
  no_found_command: "§cThe command was not found"
  # Infection message
  you_infected: "§4§lYOU ARE INFECTED!!"
  # Effect applied message
  effect-gived: "§c§lTHE INFECTION IS SPREADING"